# This file generates the GitHub Actions matrix.
# Piantor Pro BT with Miryoku layout and nice!view displays
# Builds both Linux (Ctrl) and macOS (Cmd) versions
---
include:
  # Linux version (default keymap)
  - board: piantor_pro_bt_left
    shield: nice_view
  - board: piantor_pro_bt_right
    shield: nice_view

  # macOS version (separate board variant - completely independent)
  - board: piantor_pro_bt_macos_left
    shield: nice_view
  - board: piantor_pro_bt_macos_right
    shield: nice_view

  # Settings reset
  - board: piantor_pro_bt_left
    shield: settings_reset
    snippet: studio-rpc-usb-uart
  - board: piantor_pro_bt_right
    shield: settings_reset
    snippet: studio-rpc-usb-uart
